import React, { createContext, useContext, useState, useCallback, useRef, useEffect } from "react";
import { apiFetchSSE, apiFetch } from "./useApi";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface PersonaConfig {
  name: string;
  description: string;
  philosophy: string;
  likes: string;
  dislikes: string;
}

export interface ContextImage {
  id: string;
  b64: string;
  label: string;
}

export interface ArtDirectorConfig {
  enabled: boolean;
  persona: PersonaConfig;
  verbosity: "brief" | "medium" | "detailed";
  mode: "fast" | "deep";
  systemPrompt: string;
  contextImages: ContextImage[];
}

export interface ChatMessage {
  id: string;
  role: "user" | "model";
  text: string;
  imageSnapshot?: string;
  attachedImages?: string[];
  timestamp: number;
  /** If true, this message was generated by automatic image observation */
  autoObserve?: boolean;
}

export type ApplyFeedbackFn = (suggestion: string) => void;
export type UnapplyFeedbackFn = (suggestion: string) => void;

interface ArtDirectorContextValue {
  config: ArtDirectorConfig;
  setConfig: (c: ArtDirectorConfig) => void;
  updateConfig: (partial: Partial<ArtDirectorConfig>) => void;
  messages: ChatMessage[];
  addMessage: (msg: ChatMessage) => void;
  sendMessage: (text: string, extraImages?: string[]) => Promise<void>;
  clearChat: () => void;
  isTyping: boolean;
  cancelTyping: () => void;
  currentImage: string | null;
  setCurrentImage: (src: string | null) => void;
  attributesContext: string;
  setAttributesContext: (ctx: string) => void;
  saveTranscript: (tool: string) => Promise<string | null>;
  onApplyFeedback: ApplyFeedbackFn | null;
  setOnApplyFeedback: (fn: ApplyFeedbackFn | null) => void;
  onUnapplyFeedback: UnapplyFeedbackFn | null;
  setOnUnapplyFeedback: (fn: UnapplyFeedbackFn | null) => void;
  /** Whether auto-observe is paused (user toggled off temporarily) */
  autoObservePaused: boolean;
  setAutoObservePaused: (v: boolean) => void;
}

const DEFAULT_PERSONA: PersonaConfig = {
  name: "Art Director",
  description: "",
  philosophy: "",
  likes: "",
  dislikes: "",
};

const DEFAULT_SYSTEM_PROMPT =
  "You are an AI Art Director embedded in a concept art tool. " +
  "You observe the artist's work and provide insightful, constructive, " +
  "and actionable art direction. You speak with authority and taste, " +
  "referencing composition, color theory, silhouette, mood, and storytelling.";

const DEFAULT_CONFIG: ArtDirectorConfig = {
  enabled: false,
  persona: DEFAULT_PERSONA,
  verbosity: "medium",
  mode: "fast",
  systemPrompt: DEFAULT_SYSTEM_PROMPT,
  contextImages: [],
};

const STORAGE_KEY = "madison-art-director-config";

function ensureString(v: unknown): string {
  if (Array.isArray(v)) return v.join(", ");
  return typeof v === "string" ? v : "";
}

function sanitizePersona(p: Record<string, unknown>): PersonaConfig {
  return {
    name: typeof p.name === "string" ? p.name : DEFAULT_PERSONA.name,
    description: ensureString(p.description),
    philosophy: ensureString(p.philosophy),
    likes: ensureString(p.likes),
    dislikes: ensureString(p.dislikes),
  };
}

function loadConfig(): ArtDirectorConfig {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (raw) {
      const parsed = { ...DEFAULT_CONFIG, ...JSON.parse(raw) };
      if (parsed.persona) parsed.persona = sanitizePersona(parsed.persona);
      parsed.enabled = false;
      return parsed;
    }
  } catch { /* */ }
  return { ...DEFAULT_CONFIG };
}

function persistConfig(c: ArtDirectorConfig) {
  try {
    const toSave = { ...c, contextImages: c.contextImages.map(({ id, label }) => ({ id, label, b64: "" })) };
    localStorage.setItem(STORAGE_KEY, JSON.stringify(toSave));
  } catch { /* */ }
}

// ---------------------------------------------------------------------------
// Context
// ---------------------------------------------------------------------------

const Ctx = createContext<ArtDirectorContextValue>({
  config: DEFAULT_CONFIG,
  setConfig: () => {},
  updateConfig: () => {},
  messages: [],
  addMessage: () => {},
  sendMessage: async () => {},
  clearChat: () => {},
  isTyping: false,
  cancelTyping: () => {},
  currentImage: null,
  setCurrentImage: () => {},
  attributesContext: "",
  setAttributesContext: () => {},
  saveTranscript: async () => null,
  onApplyFeedback: null,
  setOnApplyFeedback: () => {},
  onUnapplyFeedback: null,
  setOnUnapplyFeedback: () => {},
  autoObservePaused: false,
  setAutoObservePaused: () => {},
});

export const useArtDirector = () => useContext(Ctx);

const AUTO_OBSERVE_DEBOUNCE_MS = 2500;

const AUTO_OBSERVE_PROMPTS = [
  "A new image just landed on my canvas. Give me your honest creative take — what works, what could be stronger, and any ideas to push it further. Be specific and reference what you see.",
  "Fresh output on the stage. Walk me through your first impression — composition, color, mood, storytelling. Where does it sing and where can we elevate it?",
  "New generation just came in. Give me your art direction — strengths, weaknesses, and concrete suggestions. Don't hold back.",
  "Updated image on the mainstage. As my art director, tell me what you notice first, what's working, and what creative directions we could explore from here.",
  "A new version just dropped on the canvas. React to it — gut feeling, technical observations, and any bold ideas for next steps.",
];

export function ArtDirectorProvider({ children }: { children: React.ReactNode }) {
  const [config, setConfigRaw] = useState<ArtDirectorConfig>(loadConfig);
  const [messages, setMessages] = useState<ChatMessage[]>([]);
  const [isTyping, setIsTyping] = useState(false);
  const [currentImage, setCurrentImage] = useState<string | null>(null);
  const [attributesContext, setAttributesContext] = useState("");
  const [onApplyFeedback, setOnApplyFeedback] = useState<ApplyFeedbackFn | null>(null);
  const [onUnapplyFeedback, setOnUnapplyFeedback] = useState<UnapplyFeedbackFn | null>(null);
  const [autoObservePaused, setAutoObservePaused] = useState(false);
  const abortRef = useRef<AbortController | null>(null);
  const currentImageRef = useRef(currentImage);
  currentImageRef.current = currentImage;
  const lastObservedImageRef = useRef<string | null>(null);
  const autoObserveTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const isTypingRef = useRef(false);
  isTypingRef.current = isTyping;

  const setConfig = useCallback((c: ArtDirectorConfig) => {
    setConfigRaw(c);
    persistConfig(c);
  }, []);

  const updateConfig = useCallback((partial: Partial<ArtDirectorConfig>) => {
    setConfigRaw((prev) => {
      const next = { ...prev, ...partial };
      persistConfig(next);
      return next;
    });
  }, []);

  const addMessage = useCallback((msg: ChatMessage) => {
    setMessages((prev) => [...prev, msg]);
  }, []);

  const clearChat = useCallback(() => {
    abortRef.current?.abort();
    setMessages([]);
    setIsTyping(false);
  }, []);

  const cancelTyping = useCallback(() => {
    abortRef.current?.abort();
    setIsTyping(false);
  }, []);

  const sendMessage = useCallback(async (text: string, extraImages?: string[]) => {
    if (!text.trim()) return;

    if (abortRef.current) {
      abortRef.current.abort();
      abortRef.current = null;
    }

    const userMsg: ChatMessage = {
      id: crypto.randomUUID(),
      role: "user",
      text: text.trim(),
      imageSnapshot: currentImageRef.current || undefined,
      attachedImages: extraImages?.length ? extraImages : undefined,
      timestamp: Date.now(),
    };
    setMessages((prev) => [...prev, userMsg]);

    const botMsgId = crypto.randomUUID();
    const botMsg: ChatMessage = {
      id: botMsgId,
      role: "model",
      text: "",
      timestamp: Date.now(),
    };
    setMessages((prev) => [...prev, botMsg]);
    setIsTyping(true);

    const abort = new AbortController();
    abortRef.current = abort;

    const imgB64 = currentImageRef.current?.replace(/^data:image\/[^;]+;base64,/, "") || undefined;

    const inlineImages = (extraImages || []).map(
      (img) => ({ b64: img.replace(/^data:image\/[^;]+;base64,/, ""), label: "user attachment" }),
    );

    const history = messages.map((m) => ({
      role: m.role,
      text: m.text,
      image_b64: m.imageSnapshot?.replace(/^data:image\/[^;]+;base64,/, "") || undefined,
    }));

    try {
      const result = await apiFetchSSE(
        "/director/chat",
        {
          message: text.trim(),
          image_b64: imgB64,
          conversation_history: history,
          persona: sanitizePersona(config.persona as unknown as Record<string, unknown>),
          context_images: [
            ...config.contextImages.filter((ci) => ci.b64).map((ci) => ({ b64: ci.b64.replace(/^data:image\/[^;]+;base64,/, ""), label: ci.label })),
            ...inlineImages,
          ],
          attributes_context: attributesContext,
          system_prompt: config.systemPrompt,
          verbosity: config.verbosity,
          mode: config.mode,
        },
        (token) => {
          setMessages((prev) =>
            prev.map((m) => (m.id === botMsgId ? { ...m, text: m.text + token } : m)),
          );
        },
        abort.signal,
      );
      if (result.error) {
        setMessages((prev) =>
          prev.map((m) => (m.id === botMsgId ? { ...m, text: m.text || `Error: ${result.error}` } : m)),
        );
      }
    } catch (e) {
      if ((e as Error).name === "AbortError") {
        setMessages((prev) => {
          const msg = prev.find((m) => m.id === botMsgId);
          if (msg && !msg.text) return prev.filter((m) => m.id !== botMsgId);
          return prev;
        });
      } else {
        setMessages((prev) =>
          prev.map((m) => (m.id === botMsgId ? { ...m, text: m.text || "Connection error" } : m)),
        );
      }
    } finally {
      setIsTyping(false);
      abortRef.current = null;
    }
  }, [messages, config, attributesContext]);

  // --- Auto-observe: fire analysis when a new image arrives on the stage ---
  const sendAutoObserve = useCallback(async (imageB64: string) => {
    if (isTypingRef.current) return;
    const prompt = AUTO_OBSERVE_PROMPTS[Math.floor(Math.random() * AUTO_OBSERVE_PROMPTS.length)];

    const userMsg: ChatMessage = {
      id: crypto.randomUUID(),
      role: "user",
      text: prompt,
      imageSnapshot: imageB64,
      timestamp: Date.now(),
      autoObserve: true,
    };
    setMessages((prev) => [...prev, userMsg]);

    const botMsgId = crypto.randomUUID();
    const botMsg: ChatMessage = {
      id: botMsgId,
      role: "model",
      text: "",
      timestamp: Date.now(),
      autoObserve: true,
    };
    setMessages((prev) => [...prev, botMsg]);
    setIsTyping(true);

    const abort = new AbortController();
    abortRef.current = abort;

    const imgB64 = imageB64.replace(/^data:image\/[^;]+;base64,/, "");

    const history = messages.map((m) => ({
      role: m.role,
      text: m.text,
      image_b64: m.imageSnapshot?.replace(/^data:image\/[^;]+;base64,/, "") || undefined,
    }));

    try {
      const result = await apiFetchSSE(
        "/director/chat",
        {
          message: prompt,
          image_b64: imgB64,
          conversation_history: history,
          persona: sanitizePersona(config.persona as unknown as Record<string, unknown>),
          context_images: config.contextImages.filter((ci) => ci.b64).map((ci) => ({ b64: ci.b64.replace(/^data:image\/[^;]+;base64,/, ""), label: ci.label })),
          attributes_context: attributesContext,
          system_prompt: config.systemPrompt,
          verbosity: config.verbosity,
          mode: config.mode,
        },
        (token) => {
          setMessages((prev) =>
            prev.map((m) => (m.id === botMsgId ? { ...m, text: m.text + token } : m)),
          );
        },
        abort.signal,
      );
      if (result.error) {
        setMessages((prev) =>
          prev.map((m) => (m.id === botMsgId ? { ...m, text: m.text || `Error: ${result.error}` } : m)),
        );
      }
    } catch (e) {
      if ((e as Error).name === "AbortError") {
        setMessages((prev) => {
          const msg = prev.find((m) => m.id === botMsgId);
          if (msg && !msg.text) return prev.filter((m) => m.id !== botMsgId);
          return prev;
        });
      } else {
        setMessages((prev) =>
          prev.map((m) => (m.id === botMsgId ? { ...m, text: m.text || "Connection error" } : m)),
        );
      }
    } finally {
      setIsTyping(false);
      abortRef.current = null;
    }
  }, [messages, config, attributesContext]);

  // When AD is toggled on, snapshot the current image so we only react to NEW images
  const prevEnabledRef = useRef(config.enabled);
  useEffect(() => {
    if (config.enabled && !prevEnabledRef.current) {
      lastObservedImageRef.current = currentImageRef.current;
    }
    prevEnabledRef.current = config.enabled;
  }, [config.enabled]);

  useEffect(() => {
    if (!config.enabled || autoObservePaused || !currentImage) return;
    if (currentImage === lastObservedImageRef.current) return;

    if (autoObserveTimerRef.current) clearTimeout(autoObserveTimerRef.current);
    autoObserveTimerRef.current = setTimeout(() => {
      autoObserveTimerRef.current = null;
      if (!isTypingRef.current && currentImageRef.current && currentImageRef.current !== lastObservedImageRef.current) {
        lastObservedImageRef.current = currentImageRef.current;
        sendAutoObserve(currentImageRef.current);
      }
    }, AUTO_OBSERVE_DEBOUNCE_MS);

    return () => {
      if (autoObserveTimerRef.current) { clearTimeout(autoObserveTimerRef.current); autoObserveTimerRef.current = null; }
    };
  }, [currentImage, config.enabled, autoObservePaused, sendAutoObserve]);

  const saveTranscript = useCallback(async (tool: string): Promise<string | null> => {
    if (messages.length === 0) return null;
    const imageSnapshots = messages
      .filter((m) => m.imageSnapshot)
      .map((m) => m.imageSnapshot!)
      .slice(0, 5);
    try {
      const res = await apiFetch<{ id: string }>("/director/transcripts", {
        method: "POST",
        body: JSON.stringify({
          messages: messages.map((m) => ({ role: m.role, text: m.text, timestamp: m.timestamp })),
          images: imageSnapshots.map((img) => img.slice(0, 200)),
          title: `${config.persona.name} — ${new Date().toLocaleString()}`,
          tool,
        }),
      });
      return res.id;
    } catch {
      return null;
    }
  }, [messages, config.persona.name]);

  return (
    <Ctx.Provider
      value={{
        config, setConfig, updateConfig,
        messages, addMessage, sendMessage, clearChat, isTyping, cancelTyping,
        currentImage, setCurrentImage,
        attributesContext, setAttributesContext,
        saveTranscript,
        onApplyFeedback, setOnApplyFeedback,
        onUnapplyFeedback, setOnUnapplyFeedback,
        autoObservePaused, setAutoObservePaused,
      }}
    >
      {children}
    </Ctx.Provider>
  );
}
